# 07 异常处理

## 7.1 异常概述和异常体系结构

1. 异常：在Java语言中，将程序执行中发生的不正常情况称为“异常”。(开发过程中的语法错误和逻辑错误不是异常)
2.  Java程序在执行过程中所发生的异常事件可分为两类：
  - Error:Java虚拟机无法解决的严重问题。如：JVM系统内部错误、资源耗尽等严重情况。比如：StackOverflowError(栈溢出)和OOM(OutOfMemory堆溢出)。一般不编写针对性的代码进行处理。
  - Exception:其它因编程错误或偶然的外在因素导致的一般性问题，可以使用针对性的代码进行处理。    
    如: 空指针访问,试图读取不存在的文件,网络连接中断,数组角标越界

3. 异常体系结构:

java.lang.Throwable

  java.lang.Error:一般不编写针对性的代码进行处理
  java.lang.Exception:可以进行异常的处理
    
    编译时异常(checked): 
      IOException
        FileNotFoundException
      ClassNotFoundException
    运行时异常(unchecked):
      NullPointerException
      ArrayIndexOutOfBoundException
      ClassCastException
      NumberFormatException
      InputMismathcException
      ArithmaticException
      
[面试题:]常见的异常有哪些,举例说明

## 7.2 异常处理机制一:try-catch-finally

1. 异常的处理:抓抛模型

过程一:"抛":程序在正常执行的过程中,一旦出现异常,就会在异常代码出生成一个对应异常类的对象,并将此对象抛出,一旦抛出对象以后,其后的代码就不再执行

过程二:"抓":可以理解为异常的处理方式 (1)try-catch-finally (2)throws

2. try-catch-finally的使用

```
try{
    //可能出现异常的代码
    
}catch(异常类型1 变量名1){
    //处理异常的方式1
}catch(异常类型2 变量名2){
    //处理异常的方式2
}catch(异常类型3 变量名3){
    //处理异常的方式3
}
.....
finally{
    //一定会执行的代码
}
```

说明:
  - finally是可选的
  - 使用try将可能出现异常代码包装起来,在执行过程中,一旦出现异常,就会生成一个对应异常类的对象,根据此对象的类型,去catch中进行匹配\
  - 一旦try中的异常对象匹配到某一个catch时,就进入catch中进行异常的处理,一旦处理完成,就跳出当前的try-catch结构(在没有写finally的情况).继续执行其后的代码
  - catch中的异常类型如果没有子父类关系,则声明的顺序无所谓,若满足子父类关系,则要求子类一定声明在父类之上,否则会报错
  - 常用的异常对象处理的方式:(1)String Message() (2)printStackTrace()
  - 在try结构中声明的变量,在出了try之后将不能调用
  - try-catch-finally结构可以嵌套

**注意:** 
1). 使用try-catch-finally处理编译时异常,使得程序在编译时不再报错,但是运行时仍可能报错.相当于使用try-catch-finally将一个编译时可能出现的异常延迟到运行时出现
2). 开发中,由于运行时异常比较常见,所以我们通常不针对运行时异常编写try-catch-finally,针对于编译时异常,我们一定要考虑异常的处理

3. finally的使用
- finally是可选的
- finally中声明的是一定会被执行的代码,即使catch中又出现异常了,try中又return语句,catch中又return语句等情况
- 像数据库连接,输入输出流,网络编程Socket等资源,JVM是不能自动回收的,我们需要自己手动的进行资源的释放,此时的资源释放,就需要声明在finally中
